# Generated by Django 3.1.7 on 2021-03-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Профиль обучения', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Класс', models.IntegerField()),
                ('Профиль обучения', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.profile')),
            ],
        ),
    ]
