# Generated by Django 3.1.7 on 2022-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_party',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона участника'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='admission.File', verbose_name='Портфолио'),
        ),
    ]
