# Generated by Django 3.1.7 on 2021-03-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20210306_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Класс',
        ),
        migrations.AddField(
            model_name='grade',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
