# Generated by Django 3.1.7 on 2022-07-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20220425_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name', 'fathers_name']},
        ),
    ]
