# Generated by Django 3.1.7 on 2022-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20220719_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='only_olymp',
            field=models.BooleanField(default=False, verbose_name='Поступление только для олимпиадников?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='came_from_olymp_link',
            field=models.BooleanField(default=False, verbose_name='По олимпиадной ссылке пришел?'),
        ),
    ]
