# Generated by Django 3.1.7 on 2021-03-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0004_file_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTourDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата первого тура')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения абитуриента')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения абитуриента')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Школа')),
                ('fio_mother', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО мамы')),
                ('fio_father', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО отца')),
                ('phone_parent', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона одного из родителей')),
                ('out_of_competition', models.BooleanField(blank=True, default=False, null=True, verbose_name='Вне конкурса?')),
                ('reg_status', models.IntegerField(default=1, verbose_name='Статус регистрации')),
                ('activation_key', models.CharField(max_length=500, verbose_name='Ключ активации')),
                ('key_expires', models.DateTimeField(verbose_name='Срок действие ключа истекает')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('first_tour_register_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.firsttourdates', verbose_name='Выбранная дата 1 тура')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.grade', verbose_name='Класс обучения')),
                ('portfolio', models.ManyToManyField(blank=True, null=True, to='admission.File', verbose_name='Портфолио')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
