# Generated by Django 3.1.7 on 2022-12-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20220719_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttourdates',
            name='time_10',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала для 10х классов'),
        ),
        migrations.AddField(
            model_name='firsttourdates',
            name='time_7',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала для 7х классов'),
        ),
        migrations.AlterField(
            model_name='firsttourdates',
            name='date',
            field=models.DateField(verbose_name='Дата первого тура'),
        ),
    ]
