# Generated by Django 3.1.7 on 2021-03-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20210307_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lives',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город проживания'),
        ),
    ]
