# Generated by Django 3.1.7 on 2021-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_participant_lives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='phone_parent',
            new_name='phone_father',
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_mother',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона одного из родителей'),
        ),
    ]
