# Generated by Django 3.1.7 on 2021-03-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_participant_portfolio_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.profile', verbose_name='Профиль обучения'),
        ),
    ]
