# Generated by Django 3.1.7 on 2021-03-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20210312_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Класс')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.profile', verbose_name='Профиль обучения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.group', verbose_name='Класс обучения'),
        ),
    ]
