# Generated by Django 3.1.7 on 2021-03-14 12:06

import admission.helpers.validators_files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20210314_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'], message='Запрещенный формат файла.'), admission.helpers.validators_files.file_size], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='activation_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключ активации'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действие ключа истекает'),
        ),
    ]
