# Generated by Django 3.1.7 on 2021-04-06 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0016_auto_20210314_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date_privilege_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='participant',
            name='privilege_status',
            field=models.CharField(blank=True, choices=[('N', 'Не проверено'), ('R', 'Отклонено'), ('A', 'Принято')], max_length=1, null=True, verbose_name='Статус проверки льготы'),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.moderator', verbose_name='Кто проверил'),
        ),
    ]
