# Generated by Django 3.1.7 on 2021-04-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20210406_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('N', 'Не проверено'), ('R', 'Отклонено'), ('A', 'Принято')], max_length=2, verbose_name='Вердикт')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.moderator', verbose_name='Проверено')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participant', verbose_name='Участник')),
            ],
        ),
    ]
