# Generated by Django 3.1.7 on 2021-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_moderatormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_dublicate',
            field=models.BooleanField(default=False),
        ),
    ]
