# Generated by Django 3.1.7 on 2021-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_participant_is_dublicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_dublicate',
            field=models.BooleanField(default=False, verbose_name='Дубликат?'),
        ),
    ]
