# Generated by Django 3.1.7 on 2021-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20210504_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен на дублирование?'),
        ),
    ]
