# Generated by Django 3.1.7 on 2021-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_participant_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='olymp_coming_status',
            field=models.CharField(default='N', max_length=2, verbose_name='Статус прихода'),
        ),
    ]
