# Generated by Django 3.1.7 on 2021-05-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_participant_olymp_coming_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_tour_come_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пришел'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
