# Generated by Django 3.1.7 on 2021-05-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_participantregistrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='extra_score',
            field=models.IntegerField(null=True, verbose_name='Дополнительные баллы'),
        ),
    ]
