# Generated by Django 3.1.7 on 2021-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_participant_extra_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='extra_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительные баллы'),
        ),
    ]
