# Generated by Django 3.1.7 on 2021-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
    ]
