# Generated by Django 3.1.7 on 2022-04-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20220425_1008'),
        ('first_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='appeal_application',
            field=models.CharField(blank=True, choices=[('N', 'Не заявился'), ('Z', 'Заявился')], max_length=10, null=True, verbose_name='Заявился на апелляцию?'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='appeal_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Причина апелляции'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='appeal_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Апелляционный балл'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='appeal_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время апелляции'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='appeal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_tour.appealuser', verbose_name='Учителя апеллирующий'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='is_absent_appeal',
            field=models.BooleanField(default=False, verbose_name='Отсутствовал на апелляции'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время подачи заявления'),
        ),
        migrations.CreateModel(
            name='ExamSheetScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField(default=1, verbose_name='Какой тур?')),
                ('file', models.FileField(upload_to='media/ft')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participant', verbose_name='Участник')),
            ],
        ),
    ]
