# Generated by Django 3.1.7 on 2021-05-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
        ('first_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealuser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи на аппеляцию'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Результат экзамена', 'verbose_name_plural': 'Рехультаты экзаменов'},
        ),
        migrations.AlterModelOptions(
            name='examsubject',
            options={'verbose_name': 'Предмет-экзамен', 'verbose_name_plural': 'Предметы на экзамены'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='tour',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.group', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='tour',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.profile', verbose_name='Профиль'),
        ),
    ]
