# Generated by Django 3.1.7 on 2021-05-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
        ('first_tour', '0002_auto_20210518_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.profile', verbose_name='Профиль'),
        ),
        migrations.CreateModel(
            name='NextTourPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pass', models.CharField(choices=[('R', 'Резерв'), ('P', 'Прошел')], max_length=2, verbose_name='Прошел?')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participant', verbose_name='Абитуриент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
