# Generated by Django 3.1.7 on 2022-04-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0002_auto_20220425_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsheetscan',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Сканы работ'),
        ),
        migrations.AlterField(
            model_name='examsheetscan',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.tour', verbose_name='Тур'),
        ),
    ]
