# Generated by Django 3.1.7 on 2022-04-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0003_auto_20220427_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsheetscan',
            name='file',
            field=models.FileField(upload_to='scans', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'], message='Запрещенный формат файла.')], verbose_name='Сканы работ'),
        ),
    ]
