# Generated by Django 3.1.7 on 2021-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0004_examresult_appeal_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Результат экзамена', 'verbose_name_plural': 'Результаты экзаменов'},
        ),
        migrations.AddField(
            model_name='tour',
            name='final_result_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата опубликования финальных результатов'),
        ),
    ]
