# Generated by Django 3.1.7 on 2022-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0004_auto_20220427_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsheetscan',
            name='tour',
        ),
        migrations.AddField(
            model_name='examsheetscan',
            name='tour_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsheetscan',
            name='file',
            field=models.FileField(upload_to='scans', verbose_name='Сканы работ'),
        ),
    ]
