# Generated by Django 3.1.7 on 2023-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0005_auto_20220427_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='proto_appeal',
            field=models.FileField(null=True, upload_to='tours/protocols', verbose_name='Предварительынй протокол'),
        ),
        migrations.AddField(
            model_name='tour',
            name='proto_final',
            field=models.FileField(null=True, upload_to='tours/protocols', verbose_name='Финальный протокол'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tasks',
            field=models.FileField(null=True, upload_to='tours/tasks', verbose_name='Задания'),
        ),
    ]
