# Generated by Django 3.1.7 on 2021-05-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
        ('first_tour', '0005_auto_20210518_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absent_appeal', models.BooleanField(blank=True, null=True, verbose_name='Пропустил аппелляцию')),
                ('appeal_reason', models.CharField(max_length=2000, verbose_name='Причина аппелляции')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participant', verbose_name='Абитуриент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
