# Generated by Django 3.1.7 on 2023-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0006_auto_20230514_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='proto_appeal',
            field=models.FileField(blank=True, null=True, upload_to='tours/protocols', verbose_name='Предварительынй протокол'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='proto_final',
            field=models.FileField(blank=True, null=True, upload_to='tours/protocols', verbose_name='Финальный протокол'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tasks',
            field=models.FileField(blank=True, null=True, upload_to='tours/tasks', verbose_name='Задания'),
        ),
    ]
