# Generated by Django 3.1.7 on 2021-05-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0006_userappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='appeal_application_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия доступа к аппелляции'),
        ),
    ]
