# Generated by Django 3.1.7 on 2023-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0007_auto_20230514_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='recommended_to_enter',
            field=models.FileField(blank=True, null=True, upload_to='tours/protocols', verbose_name='Список рекомендованных'),
        ),
    ]
