# Generated by Django 3.1.7 on 2021-05-18 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0008_userappeal_appeal_apply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='min_score',
            field=models.IntegerField(default=0, verbose_name='Минимальный балл'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 22, 29, 59, 20954), verbose_name='Время подачи заявления'),
        ),
    ]
