# Generated by Django 3.1.7 on 2025-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0008_tour_recommended_to_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='all_students_in_rating',
            field=models.BooleanField(default=False, verbose_name='Все ученики участвуют в рейтинге?'),
        ),
    ]
