# Generated by Django 3.1.7 on 2025-04-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0009_tour_all_students_in_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='use_extra_score',
            field=models.BooleanField(default=False, verbose_name='Использовать дополнительные баллы?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='use_photos',
            field=models.BooleanField(default=False, verbose_name='Использовать фотографии в итоговой таблице?'),
        ),
    ]
