# Generated by Django 3.1.7 on 2021-05-20 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0010_auto_20210520_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='appeal_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на апелляцию'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 1, 8, 8, 378099), verbose_name='Время подачи заявления'),
        ),
    ]
