# Generated by Django 3.1.7 on 2025-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0010_auto_20250411_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='allways_show_id_in_final_table',
            field=models.BooleanField(default=True, verbose_name='Показывать ID  в итоговой таблице?'),
        ),
    ]
