# Generated by Django 3.1.7 on 2021-05-20 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0012_auto_20210520_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 12, 40, 0, 655186), verbose_name='Время подачи заявления'),
        ),
    ]
