# Generated by Django 3.1.7 on 2025-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0012_tour_make_max_score_for_olympiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='user_liter_grades',
            field=models.BooleanField(default=False, verbose_name='Используются классы в итоговой таблице?'),
        ),
    ]
