# Generated by Django 3.1.7 on 2025-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0013_tour_user_liter_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexttourpass',
            name='hidden_in_table',
            field=models.BooleanField(default=False, verbose_name='Скрыт в таблице результатов?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='show_hidden_participants',
            field=models.BooleanField(default=True, verbose_name='Показывать скрытых участников'),
        ),
    ]
