# Generated by Django 3.1.7 on 2021-05-20 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0014_auto_20210520_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(verbose_name='Набранный балл'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 18, 52, 40, 99342), verbose_name='Время подачи заявления'),
        ),
    ]
