# Generated by Django 3.1.7 on 2021-05-20 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0015_auto_20210520_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 16, 16, 914592), verbose_name='Время подачи заявления'),
        ),
    ]
