# Generated by Django 3.1.7 on 2021-05-24 15:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
        ('first_tour', '0016_auto_20210520_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 15, 54, 26, 874676), verbose_name='Время подачи заявления'),
        ),
        migrations.CreateModel(
            name='UploadConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pps', models.FileField(upload_to='confirm/pps', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'], message='Запрещенный формат файла.')], verbose_name='Согласие на психолого-педагогическое сбеседование')),
                ('agreement_tour', models.FileField(upload_to='confirm/agreement', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'], message='Запрещенный формат файла.')], verbose_name='Согласие на участие во 2 туре вступительных испытаний')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participant', verbose_name='Абитуриент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
