# Generated by Django 3.1.7 on 2021-05-24 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20210517_2332'),
        ('first_tour', '0017_auto_20210524_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 17, 36, 57, 349029), verbose_name='Время подачи заявления'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadconfirm',
            unique_together={('participant', 'tour')},
        ),
    ]
