# Generated by Django 3.1.7 on 2021-05-29 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0020_auto_20210529_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexttourpass',
            name='has_come',
            field=models.BooleanField(default=False, verbose_name='Пришел?'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 18, 13, 55, 150016), verbose_name='Время подачи заявления'),
        ),
    ]
