# Generated by Django 3.1.7 on 2021-05-29 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_participant_profile_photo'),
        ('first_tour', '0021_auto_20210529_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 18, 39, 8, 103479), verbose_name='Время подачи заявления'),
        ),
        migrations.CreateModel(
            name='LiterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Литер')),
                ('participants', models.ManyToManyField(to='admission.Participant', verbose_name='Ученики')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
