# Generated by Django 3.1.7 on 2021-05-29 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0022_auto_20210529_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('tour_ordering', models.IntegerField(verbose_name='Очередность тура')),
            ],
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 20, 35, 24, 763451), verbose_name='Время подачи заявления'),
        ),
    ]
