# Generated by Django 3.1.7 on 2021-05-29 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_participant_profile_photo'),
        ('first_tour', '0023_auto_20210529_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litergrade',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='admission.Participant', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 20, 37, 29, 22355), verbose_name='Время подачи заявления'),
        ),
    ]
