# Generated by Django 3.1.7 on 2021-05-29 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_participant_profile_photo'),
        ('first_tour', '0024_auto_20210529_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litergrade',
            name='participants',
            field=models.ManyToManyField(blank=True, to='admission.Participant', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 21, 8, 13, 126912), verbose_name='Время подачи заявления'),
        ),
    ]
