# Generated by Django 3.1.7 on 2021-06-01 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_tour', '0025_auto_20210529_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='appeal_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Аппелляционный балл'),
        ),
        migrations.AlterField(
            model_name='userappeal',
            name='appeal_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 22, 14, 10, 980850), verbose_name='Время подачи заявления'),
        ),
    ]
