# Generated by Django 3.1.7 on 2022-05-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_tour', '0005_auto_20220427_1259'),
        ('admission', '0002_auto_20220425_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiterGradeTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litergrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_tour.litergrade', verbose_name='группа')),
                ('participantregistrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.participantregistrator', verbose_name='регистратор')),
            ],
            options={
                'verbose_name': 'группу II тура',
                'verbose_name_plural': 'группы II тура',
            },
        ),
    ]
