"""
Django settings for itlAdmissionProject project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import datetime
import os
import platform
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mst2^99(_vvq81-5!$f*kh@je)2jq2jhf6a)uqk(_*b)9fmrq^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admission.apps.AdmissionConfig',
    'crispy_forms',
    'bootstrap4',
    'upload_test_app.apps.UploadTestAppConfig',
    'first_tour.apps.FirstTourConfig',
    'admin_profile.apps.AdminProfileConfig',
    'api.apps.ApiConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itlAdmissionProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itlAdmissionProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'admission_2022',
        'USER': 'admission',
        'PASSWORD': '1q2w!Q@W',
        'HOST': 'localhost',
        'PORT': '',
    }
}
if platform.system() in ['Darwin', 'win32']:
    DEBUG = True
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME': os.path.join(BASE_DIR, 'admission.data'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = '/proxy/'
LOGIN_URL = '/login/'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'apply-itl@itl4u.ru'
# EMAIL_HOST_PASSWORD = 'UUxlh284'

EMAIL_USE_TLS = True
EMAIL_HOST = 'ex.kpfu.ru'
EMAIL_PORT = 587
EMAIL_HOST_USER = r'apply-itl'
EMAIL_HOST_PASSWORD = '7gse5bEU9Y'
SERVER_EMAIL = 'apply-itl@kpfu.ru'  # EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = SERVER_EMAIL

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MAIN_HOST = "https://apply.kpfu.ru/"
DOMAIN = 'apply.kpfu.ru'
PROTOCOL = 'https'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'media')
ALLOWED_EXTENSIONS = ['pdf', 'jpeg', 'jpg', 'png']
FILE_SIZE_LIMIT = 2 * 1024 * 1024  # 2 MB
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
REGISTER_END_DATE = datetime.date(2022, 4, 23)
APPEAL_START_TIME = datetime.datetime(2023, 5, 22, 13, 0, 0)
APPEAL_ANNOUNCE_TIME = datetime.datetime(2023, 5, 22, 12, 30, 0)
APPEAL_PERIOD_MINUTES = 5
# REDIS related settings
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_IMPORTS = [
    'first_tour.task',
    'admission.task'
]

SALT = 'zxsaqwwqasxz'

FILES_COUNT_LIMIT = 10
